ElasticsearchCore/Models/BookModel.cs
namespace ElasticsearchCore.Models
{
    public class BookModel
    {
        public string Title { get; set; }

        public string Isbn { get; set; }

        public int PageCount { get; set; }

        public string ThumbnailUrl { get; set; }

        public string ShortDescription { get; set; }

        public string LongDescription { get; set; }

        public string Status { get; set; }

        public string Authors { get; set; }

        public string Categories { get; set; }
    }
}

ElasticsearchCore/Models/BookViewModel.cs
namespace ElasticsearchCore.Models
{
    public class BookViewModel
    {
        public string Title { get; set; }

        public string Isbn { get; set; }

        public int PageCount { get; set; }

        public string ThumbnailUrl { get; set; }

        public string ShortDescription { get; set; }

        public string LongDescription { get; set; }

        public string Status { get; set; }

        public string Authors { get; set; }

        public string Categories { get; set; }
    }
}

ElasticsearchCore/Models/ErrorModel.cs
using System;

namespace ElasticsearchCore.Models
{
    public class ErrorModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

ElasticsearchCore/Models/ErrorViewModel.cs
using System;

namespace ElasticsearchCore.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

ElasticsearchCore/Controllers/MainController.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using ElasticsearchCore.Models;
using Nest;

namespace ElasticsearchCore.Controllers
{
    public class MainController : Controller
    {
        private readonly ILogger<MainController> FLogger;
        
        private readonly ElasticClient FClient;

        public MainController(ILogger<MainController> ALogger, ElasticClient AClient)
        {
            FLogger = ALogger;
            FClient = AClient;
        }

        public IActionResult Index() => View();

        /// <summary>
        /// Return book that contains searched text in Title field; or first ten books.
        /// </summary>
        /// <param name="AInputQuery"></param>
        /// <returns></returns>
        public IActionResult TitleSearch(string AInputQuery)
        {
            if (!string.IsNullOrWhiteSpace(AInputQuery)) 
            {
                var LShowResult = FClient
                    .Search<BookModel>(ASearch => ASearch
                    .Query(AQuery => AQuery
                    .Match(AMatch => AMatch
                    .Field(ABookModel => ABookModel.Title)
                    .Query(AInputQuery))));

                FLogger.LogInformation("{AInputQuery}",$"Searched phrase: {AInputQuery}");
                return View(LShowResult);
            }

            FLogger.LogInformation("Display first ten results");
            var LShowAll = FClient
                .Search<BookModel>(ASearch => ASearch
                .Query(AQuery => AQuery
                .MatchAll()));

            return View(LShowAll);
        }

        /// <summary>
        /// Aggregation of "pageCounts" field.
        /// </summary>
        /// <returns></returns>
        public IActionResult PageCount() 
        {
            FLogger.LogInformation("Return page counts");
            return View(FClient.Search<BookModel>(ASearch => ASearch
                .Query(AQuery => AQuery
                .MatchAll())
                .Aggregations(AAggregate => AAggregate
                .Range("pageCounts", ARange => ARange
                .Field(ABookModel => ABookModel.PageCount)
                .Ranges(ARanges => ARanges
                    .From(0), ARanges => ARanges
                    .From(200).To(400), ARanges => ARanges
                    .From(400).To(600), ARanges => ARanges
                    .From(600))))));
        }

        /// <summary>
        /// Aggregation of filtered "categories" term.
        /// </summary>
        /// <returns></returns>
        public IActionResult Categories() 
        {
            FLogger.LogInformation("Return aggregation of filtered terms");
            return View(FClient.Search<BookModel>(ASearch => ASearch
                .Query(AQuery => AQuery
                .MatchAll())
                .Aggregations(AAggregate => AAggregate
                .Terms("categories", ATerms => ATerms
                .Field("categories.keyword")))));
        }

        public IActionResult Privacy() => View();

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorModel 
            { 
                RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier 
            });
        }
    }
}

ElasticsearchCore/Views/Main/Categories.cshtml
@model Nest.ISearchResponse<BookModel>

<br />
@if (Model.Aggregations != null)
{
    <h4>Aggregations</h4>
    <br />
    @if (Model.Aggregations.ContainsKey("categories"))
    {
        <h4>Categories (Terms)</h4>
        <ul>
            @foreach (var LBucket in Model.Aggregations.Terms("categories").Buckets)
            {
                <li>@LBucket.Key: @LBucket.DocCount</li>
            }
        </ul>
    }
}

ElasticsearchCore/Views/Main/Index.cshtml
<dv>
    <p>
        Example of the popular open-source search and analytics engine – Elasticsearch to power a simple search system in ASP.NET Core.
    </p>
</dv>
<hr />
<div>
    <p>
        Few key features follows:
    </p>
    <ul>
        <li>
            Distributed and scalable, including the ability for sharding and replicas.
        </li>
        <li>
            Documents uses JSON format.
        </li>
        <li>
            All interactions are done over a REST API.
        </li>
        <li>
            Many software like popular Kibana which allows interrogation and analysis of data.
        </li>
        <li>
            Loads of client-side libraries for all popular languages.
        </li>
    </ul>
</div>
<hr />
<div>
    <p>
        Example pages:
    </p>
    <ul>
        <li>
            Title Search - allow to search via Title, when no "Term" is given, then we return first ten books from the database. For given search text, we return items that contains searched text.
        </li>
        <li>
            Page Count - This page returns range aggregation of the books pages (this is done by using "Aggregate" function).
        </li>
        <li>
            Categories - This page returns total count for appearing categories (aggregation on text fields) in the whole database.
        </li>
    </ul>
</div>
<hr />
<div>
    <p>
        Single index in example dataset:
    </p>

    <!-- HTML generated using hilite.me -->
    <div style="background: #ffffff; overflow:auto;width:auto;border:solid gray;border-width:.1em .1em .1em .8em;padding:.2em .6em;">
<pre style="margin: 0; line-height: 125%">
{ 
    <span style="color: #007700">&quot;title&quot;</span>:<span style="background-color: #fff0f0">&quot;string&quot;</span>, 
    <span style="color: #007700">&quot;isbn&quot;</span>:<span style="background-color: #fff0f0">&quot;string&quot;</span>, 
    <span style="color: #007700">&quot;pageCount&quot;</span>:<span style="color: #0000DD; font-weight: bold">0</span>, 
    <span style="color: #007700">&quot;thumbnailUrl&quot;</span>:<span style="background-color: #fff0f0">&quot;string&quot;</span>, 
    <span style="color: #007700">&quot;shortDescription&quot;</span>:<span style="background-color: #fff0f0">&quot;string&quot;</span>, 
    <span style="color: #007700">&quot;longDescription&quot;</span>:<span style="background-color: #fff0f0">&quot;string&quot;</span>, 
    <span style="color: #007700">&quot;status&quot;</span>:<span style="background-color: #fff0f0">&quot;string&quot;</span>, 
    <span style="color: #007700">&quot;authors&quot;</span>:<span style="background-color: #fff0f0">&quot;string&quot;</span>, 
    <span style="color: #007700">&quot;categories&quot;</span>:<span style="background-color: #fff0f0">&quot;string&quot;</span> 
}
</pre>
    </div>
    <!-- HTML generated using hilite.me -->

    <br />
    <p>
        Assuming you are running Elasticsearch engine in Docker on port 9200, to load your own dataset from JSON file, execute following command:
    </p>

<!-- HTML generated using hilite.me -->
<div style="background: #ffffff; overflow:auto;width:auto;border:solid gray;border-width:.1em .1em .1em .8em;padding:.2em .6em;">
<pre style="margin: 0; line-height: 125%">
curl -XPOST localhost:9200/books/book/_bulk --data-binary @@dataset.json -H <span style="background-color: #fff0f0">&quot;Content-Type: application/json&quot;</span>
</pre>
</div>
<!-- HTML generated using hilite.me -->

    <br />
    <p>
        Please note: ensure that your file will have empty newline and the end of the file.
    </p>

</div>

ElasticsearchCore/Views/Main/PageCount.cshtml
@model Nest.ISearchResponse<BookModel>

<br />
@if (Model.Aggregations != null)
{
    <h4>Aggregations</h4>
    <br />
    @if (Model.Aggregations.ContainsKey("pageCounts"))
    {
        <h4>Page Count (Ranges)</h4>
        <ul>
            @foreach (var LBucket in Model.Aggregations.Range("pageCounts").Buckets)
            {
                <li>@LBucket.Key: @LBucket.DocCount</li>
            }
        </ul>
    }
}

ElasticsearchCore/Views/Main/TitleSearch.cshtml
@model Nest.ISearchResponse<BookModel>

<br />
<h4>Search Title field:</h4>
<form asp-controller="Main" asp-action="TitleSearch" method="post">
    <input type="text" name="AInputQuery" />
    <input type="submit" value="Search" />
</form>

@if (Model.Documents.Any())
{
    <br />
    <h4>Search Results:</h4>
    <br />
    <ul>
        @foreach (var LBook in Model.Documents)
        {
            <li>Title: @LBook.Title (ISBN: @LBook.Isbn)</li>
        }
    </ul>
}

ElasticsearchCore/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Elasticsearch Core</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Main" asp-action="Index">Elasticsearch Core</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Main" asp-action="TitleSearch">Title Search</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Main" asp-action="PageCount">Page Count</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Main" asp-action="Categories">Categories</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Main" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>
    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2021 - Elasticsearch Core - <a asp-area="" asp-controller="Main" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>